# Use root/example as user/password credentials
version: '3.1'


services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: dev-user
      POSTGRES_DB: freezer-dev
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
