// <auto-generated />
using System;
using BlazingFreezer.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BlazingFreezer.API.Migrations
{
    [DbContext(typeof(FreezerDataContext))]
    [Migration("20200628183100_ExtraData")]
    partial class ExtraData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BlazingFreezer.API.Models.Freezer", b =>
                {
                    b.Property<int>("FreezerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("FreezerId");

                    b.ToTable("Freezers");

                    b.HasData(
                        new
                        {
                            FreezerId = 1,
                            Name = "Keuken"
                        },
                        new
                        {
                            FreezerId = 2,
                            Name = "Garage"
                        });
                });

            modelBuilder.Entity("BlazingFreezer.API.Models.FreezerDrawer", b =>
                {
                    b.Property<int>("FreezerDrawerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FreezerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("FreezerDrawerId");

                    b.HasIndex("FreezerId");

                    b.ToTable("FreezerDrawers");

                    b.HasData(
                        new
                        {
                            FreezerDrawerId = 1,
                            FreezerId = 1,
                            Name = "Bovenaan"
                        },
                        new
                        {
                            FreezerDrawerId = 2,
                            FreezerId = 1,
                            Name = "Onderaan"
                        },
                        new
                        {
                            FreezerDrawerId = 3,
                            FreezerId = 2,
                            Name = "Schuif 1"
                        },
                        new
                        {
                            FreezerDrawerId = 4,
                            FreezerId = 2,
                            Name = "Schuif 2"
                        },
                        new
                        {
                            FreezerDrawerId = 5,
                            FreezerId = 2,
                            Name = "Schuif 3"
                        },
                        new
                        {
                            FreezerDrawerId = 6,
                            FreezerId = 2,
                            Name = "Schuif 4"
                        },
                        new
                        {
                            FreezerDrawerId = 7,
                            FreezerId = 2,
                            Name = "Schuif 5"
                        },
                        new
                        {
                            FreezerDrawerId = 8,
                            FreezerId = 2,
                            Name = "Schuif 6"
                        },
                        new
                        {
                            FreezerDrawerId = 9,
                            FreezerId = 2,
                            Name = "Schuif 7"
                        });
                });

            modelBuilder.Entity("BlazingFreezer.API.Models.FreezerItem", b =>
                {
                    b.Property<int>("FreezerItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FreezerDrawerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVacuum")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Since")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("FreezerItemId");

                    b.HasIndex("FreezerDrawerId");

                    b.ToTable("FreezerItems");
                });

            modelBuilder.Entity("BlazingFreezer.API.Models.FreezerDrawer", b =>
                {
                    b.HasOne("BlazingFreezer.API.Models.Freezer", null)
                        .WithMany("FreezerDrawers")
                        .HasForeignKey("FreezerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazingFreezer.API.Models.FreezerItem", b =>
                {
                    b.HasOne("BlazingFreezer.API.Models.FreezerDrawer", null)
                        .WithMany("FreezerItems")
                        .HasForeignKey("FreezerDrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
